name: deploy-auth

on:
  push:
     branches: 
       - main
     paths:
       - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t xxhashanxx/auth .
      - run: docker login -u xxhashanxx -p Hashan123@Docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSOWRD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push xxhashanxx/auth
